<h1 id="privacy"><%= resourceBundles.getString("Privacy Policy") %></h1>
<h2><%= resourceBundles.getString("General Information") %></h2>
<p>
  <%= resourceBundles.getString("With this privacy policy Irish Dictionary Online provides information to data subjects on the processing of their personal data, as required by the EU General Data Protection Regulation (“GDPR”).") %>
</p>
<h2><%= resourceBundles.getString("Contact Information") %></h2>
<p>
  <%= resourceBundles.getString("Name:") %> <%= resourceBundles.getString("Irish Dictionary Online Limited S.A.") %>
  <br/><%= resourceBundles.getString("Address:") %> 773 Calle Enrique Linares, Balboa, Ancon, Panama City, Panama
  <br/><%= resourceBundles.getString("Email:") %> info@englishirishdictionary.com
  <br/><%= resourceBundles.getString("Contact person:") %> Mr. Dermot Doherty (dermot@englishirishdictionary.com / +52 415 167 4538)
</p>
<%--h2><%= resourceBundles.getString("Purpose And Legal Basis For Personal Data Processing") %></h2--%>
<h2 id="cookies"><%= resourceBundles.getString("Cookie Policy") %></h2>
<p>
  <strong><%= resourceBundles.getString("What is a cookie?") %></strong>
  <br/>
  <%= resourceBundles.getString("A cookie is a small piece of data stored in a file on a users computer.") %>
  <%= resourceBundles.getString("As with all cookies they are harmless to your computer and can be deleted easily.") %>
  <br/><strong><%= resourceBundles.getString("How and when do we use cookies?") %></strong>
   <%--that allows us to identify a client browser when it visits this website.--%>
  <br/><%= resourceBundles.getString("Irish Dictionary Online creates a session cookie called 'JSESSIONID' when a user accesses this website.") %>
  <%= resourceBundles.getString("This session cookie is currently used for two purposes:") %>
  <ol>
    <li><%= resourceBundles.getString("to remember the users language preference, if selected") %></li>
    <li><%= resourceBundles.getString("to remember if the user has consented to the use of cookies") %></li>
  </ol>
  <%--= resourceBundles.getString("Irish Dictionary Online is not currently using this cookie to personally identify the user or record their activity.") --%>
  <br/><strong style="padding: 10px 0px;"><%= resourceBundles.getString("Third party cookies") %></strong>
  <br/>This site uses Google Analytics, a web analytics service that uses cookies to help to analyze how users use the site. The information generated by the cookie about your use of this website (including your IP address) will be transmitted to and recorded by Google. Google will use this information for the purpose of evaluating your use of this website, compiling reports on website activity, and providing other services relating to website activity and internet usage. Google may also transfer this information to third parties where required to do so by law, or where such third parties process the information on Google’s behalf. Google undertakes not to associate your IP address with any other data held by Google.
</p>

<h2><%= resourceBundles.getString("Changes to this Privacy Policy and Cookie Policy") %></h2>
<p>
  <%= resourceBundles.getString("Irish Dictionary Online reserves the right in its sole discretion to amend these terms and privacy statement at any time.") %>
  <%--= resourceBundles.getString("If a change is made to these terms or privacy policy you will be notified of that change and your agreement and acceptance of that change will be requested.") --%>
</p>